import OrderForm from "@/components/OrderForm";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "GoStudent",
  description: "Generated by Yasmine El-shahat",
};

export default function Home() {
  return <OrderForm />;
}
